name: Fix code style

on:
  # Triggers the workflow on push or pull request events but only for the 1.x branch
  push:
    paths:
      - '**.php'
    branches: [ 1.x ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fix_style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      - name: Fix code style
        run: ./vendor/bin/pint

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: GitHub Actions
          commit_message: Fixed code style
          file_pattern: ./**.php
